Build: fix no-pch error
/home/runner/work/EG-Source/EG-Source/src/server/game/Custom/CustomFunctions.cpp: In member function ‘bool Vehicle::NormalizePassengerMovementInfo(const Unit*, MovementInfo&) const’:
/home/runner/work/EG-Source/EG-Source/src/server/game/Custom/CustomFunctions.cpp:222:13: error: ‘TC_LOG_WARN’ was not declared in this scope
  222 |             TC_LOG_WARN("vehicles", "VehicleSeat ID {} has VEHICLE_SEAT_FLAG_ALLOW_TURNING but no VehicleSeatAddon DB row; orientation offset defaults to 0.0f", seatInfo->ID);
      |             ^~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:1003: src/server/game/CMakeFiles/game.dir/Custom/CustomFunctions.cpp.o] Error 1