Build: fix no pch
/home/runner/work/EG-Source/EG-Source/src/server/scripts/Custom/Spells/EG_gen_spell_scripts.cpp: In member function ‘void EG_spell_deploy_salvage_saws::SelectRandomTargetDest(SpellDestination&)’:
/home/runner/work/EG-Source/EG-Source/src/server/scripts/Custom/Spells/EG_gen_spell_scripts.cpp:283:40: error: invalid use of incomplete type ‘class CreatureAI’
  283 |         if (Unit* target = caster->AI()->SelectTarget(SelectTargetMethod::Random, 0, 40.0f, true))
      |                                        ^~
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/server/scripts/CMakeFiles/scripts_custom.dir/build.make:233: src/server/scripts/CMakeFiles/scripts_custom.dir/Custom/Spells/EG_gen_spell_scripts.cpp.o] Error 1