Build: fix compile error
In file included from /home/runner/work/EG-Source/EG-Source/src/server/game/Maps/Map.cpp:32:
/home/runner/work/EG-Source/EG-Source/src/server/game/Maps/Map.cpp: In member function ‘void InstanceMap::PermBindAllPlayers()’:
/home/runner/work/EG-Source/EG-Source/src/server/game/Maps/Map.cpp:4186:30: error: ‘const class InstanceScript’ has no member named ‘GetEncounterStateNames’
 4186 |             script ? script->GetEncounterStateNames() : "no-script");
      |                              ^~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/EG-Source/EG-Source/src/common/Logging/Log.h:140:57: note: in definition of macro ‘TC_LOG_MESSAGE_BODY’
  140 |                 sLog->OutMessage(filterType__, level__, __VA_ARGS__);   \
      |                                                         ^~~~~~~~~~~
/home/runner/work/EG-Source/EG-Source/src/server/game/Maps/Map.cpp:4179:9: note: in expansion of macro ‘TC_LOG_ERROR’
 4179 |         TC_LOG_ERROR("maps", "Cannot bind players to instance map (Name: {}, Entry: {}, Difficulty: {}, ID: {}) because no instance save is available! "
      |         ^~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:2403: src/server/game/CMakeFiles/game.dir/Maps/Map.cpp.o] Error 1