Build: fix warning
/home/runner/work/EG-Source/EG-Source/src/server/game/Movement/MovementGenerators/FollowMovementGenerator.cpp: In member function ‘virtual bool FollowMovementGenerator::Update(Unit*, uint32)’:
/home/runner/work/EG-Source/EG-Source/src/server/game/Movement/MovementGenerators/FollowMovementGenerator.cpp:175:20: error: unused variable ‘angleOkayRelaxed’ [-Werror=unused-variable]
  175 |         bool const angleOkayRelaxed = AngleOkayRelaxed(_angle, curAngle, 0.15f);
      |                    ^~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:2725: src/server/game/CMakeFiles/game.dir/Movement/MovementGenerators/FollowMovementGenerator.cpp.o] Error 1