Build: fix compile error
/home/runner/work/EG-Source/EG-Source/src/server/game/Handlers/MovementHandler.cpp: In member function ‘void WorldSession::HandleMoveWorldportAck()’:
/home/runner/work/EG-Source/EG-Source/src/server/game/Handlers/MovementHandler.cpp:294:49: error: ‘class BattlefieldMgr’ has no member named ‘GetEnabledBattlefield’
  294 |     Battlefield* battlefield = sBattlefieldMgr->GetEnabledBattlefield(newzone);
      |                                                 ^~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:2067: src/server/game/CMakeFiles/game.dir/Handlers/MovementHandler.cpp.o] Error 1