Build: fix warning
/home/runner/work/EG-Source/EG-Source/src/server/scripts/Custom/EG_player_scripts.cpp:64:34: error: unused variable ‘worldChannel’ [-Werror=unused-variable]
   64 |                     if (Channel* worldChannel = cMgr->GetCustomChannel(std::string(WORLD_CHAT)))
      |                                  ^~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors

well this one is funny