Build: fix no-pch error
/home/runner/work/EG-Source/EG-Source/src/server/scripts/Custom/NPCs/EG_gen_npc_scripts.cpp: In member function ‘virtual void EG_npc_crystalline_frayer::EnterEvadeMode(CreatureAI::EvadeReason)’:
/home/runner/work/EG-Source/EG-Source/src/server/scripts/Custom/NPCs/EG_gen_npc_scripts.cpp:769:34: error: invalid use of incomplete type ‘class MotionMaster’
  769 |             me->GetMotionMaster()->Clear();
      |                                  ^~
compilation terminated due to -Wfatal-errors.