Build: fix build error
how on earth did this not pop before?

/home/runner/work/EG-Source/EG-Source/src/server/scripts/Northrend/zone_storm_peaks.cpp: In member function ‘virtual void npc_wild_wyrm::DoAction(int32)’:
/home/runner/work/EG-Source/EG-Source/src/server/scripts/Northrend/zone_storm_peaks.cpp:575:31: error: no matching function for call to ‘npc_wild_wyrm::EnterEvadeMode()’
  575 |                 EnterEvadeMode();
      |                 ~~~~~~~~~~~~~~^~
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/server/scripts/CMakeFiles/scripts_northrend.dir/build.make:191: src/server/scripts/CMakeFiles/scripts_northrend.dir/Northrend/zone_storm_peaks.cpp.o] Error 1