Build: fix warning
/home/runner/work/EG-Source/EG-Source/src/server/game/Spells/Auras/SpellAuraEffects.cpp: In member function ‘void AuraEffect::HandleAuraTransform(const AuraApplication*, uint8, bool) const’:
/home/runner/work/EG-Source/EG-Source/src/server/game/Spells/Auras/SpellAuraEffects.cpp:2104:28: error: suggest explicit braces to avoid ambiguous ‘else’ [-Werror=dangling-else]
 2104 |                         if (Unit* caster = GetCaster())
      |                            ^
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:3663: src/server/game/CMakeFiles/game.dir/Spells/Auras/SpellAuraEffects.cpp.o] Error 1