Build: fix no pch error
/home/runner/work/EG-Source/EG-Source/src/server/scripts/Custom/NPCs/EG_gen_npc_scripts.cpp: In member function ‘void EG_npc_kologarn_focused_eyebeam::ChaseSharedTarget()’:
/home/runner/work/EG-Source/EG-Source/src/server/scripts/Custom/NPCs/EG_gen_npc_scripts.cpp:1457:51: error: invalid use of incomplete type ‘class InstanceScript’
 1457 |         Creature* kologarn = _instance ? _instance->GetCreature(DATA_KOLOGARN) : nullptr;
      |                                                   ^~
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/server/scripts/CMakeFiles/scripts_custom.dir/build.make:205: src/server/scripts/CMakeFiles/scripts_custom.dir/Custom/NPCs/EG_gen_npc_scripts.cpp.o] Error 1