Build: fix no pch error
/home/runner/work/EG-Source/EG-Source/src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/instance_obsidian_sanctum.cpp: In member function ‘virtual void instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::OnCreatureCreate(Creature*)’:
/home/runner/work/EG-Source/EG-Source/src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/instance_obsidian_sanctum.cpp:75:56: error: invalid use of incomplete type ‘class InstanceMap’
   75 |                     if (Creature* sartharion = instance->GetCreature(GetGuidData(DATA_SARTHARION)))
      |                                                        ^~
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/server/scripts/CMakeFiles/scripts_northrend.dir/build.make:401: src/server/scripts/CMakeFiles/scripts_northrend.dir/Northrend/ChamberOfAspects/ObsidianSanctum/instance_obsidian_sanctum.cpp.o] Error 1