Build: fix incorrect container usage
In file included from /usr/include/c++/11/vector:62,
                 from /home/runner/work/EG-Source/EG-Source/src/server/shared/DataStores/DBCEnums.h:22,
                 from /home/runner/work/EG-Source/EG-Source/src/server/shared/SharedDefines.h:21,
                 from /home/runner/work/EG-Source/EG-Source/src/server/game/Custom/CustomFunctions.h:5,
                 from /home/runner/work/EG-Source/EG-Source/src/server/game/Custom/CustomFunctions.cpp:1:
/usr/include/c++/11/bits/stl_algo.h: In instantiation of ‘void std::shuffle(_RAIter, _RAIter, _UGenerator&&) [with _RAIter = std::_List_iterator<Unit*>; _UGenerator = RandomEngine&]’:
/home/runner/work/EG-Source/EG-Source/src/common/Utilities/Containers.h:168:25:   required from ‘void Trinity::Containers::RandomShuffle(C&) [with C = std::__cxx11::list<Unit*>]’
/home/runner/work/EG-Source/EG-Source/src/server/game/Custom/CustomFunctions.cpp:666:39:   required from here
/usr/include/c++/11/bits/stl_algo.h:3753:51: error: no match for ‘operator-’ (operand types are ‘std::_List_iterator<Unit*>’ and ‘std::_List_iterator<Unit*>’)
 3753 |       const __uc_type __urange = __uc_type(__last - __first);
      |                                            ~~~~~~~^~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:1017: src/server/game/CMakeFiles/game.dir/Custom/CustomFunctions.cpp.o] Error 1

(cherry picked from commit 66f0251b90b56ec76980050efa6a8360a396e3f8)