Build: fix error
/home/runner/work/EG-Source/EG-Source/src/server/game/Movement/MovementGenerators/FollowMovementGenerator.cpp: In member function ‘virtual bool FollowMovementGenerator::Update(Unit*, uint32)’:
/home/runner/work/EG-Source/EG-Source/src/server/game/Movement/MovementGenerators/FollowMovementGenerator.cpp:138:70: error: invalid use of incomplete type ‘class Player’
  138 |                 else if (owner->IsPet() && owner->ToPet()->GetOwner()->GetGUID() == target->GetGUID())
      |                                                                      ^~
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:2697: src/server/game/CMakeFiles/game.dir/Movement/MovementGenerators/FollowMovementGenerator.cpp.o] Error 1