Build: fix compile error
/home/runner/work/EG-Source/EG-Source/src/server/game/DungeonFinding/LFGMgr.cpp: In member function ‘bool lfg::LFGMgr::TryFinishDungeonFromCurrentInstance(Group*)’:
/home/runner/work/EG-Source/EG-Source/src/server/game/DungeonFinding/LFGMgr.cpp:437:105: error: ‘class Map’ has no member named ‘GetDifficulty’; did you mean ‘GetDifficultyID’?
  437 |         DungeonEncounterList const* encounters = sObjectMgr->GetDungeonEncounterList(map->GetId(), map->GetDifficulty());
      |                                                                                                         ^~~~~~~~~~~~~
      |                                                                                                         GetDifficultyID
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:1115: src/server/game/CMakeFiles/game.dir/DungeonFinding/LFGMgr.cpp.o] Error 1