Build: fix build error
/home/runner/work/EG-Source/EG-Source/src/server/scripts/Northrend/Ulduar/Ulduar/boss_thorim.cpp: In member function ‘virtual void boss_thorim::Reset()’:
/home/runner/work/EG-Source/EG-Source/src/server/scripts/Northrend/Ulduar/Ulduar/boss_thorim.cpp:500:54: error: cannot convert ‘TempSummon*’ to ‘Creature*’ in initialization
  500 |             if (Creature* preAdd = me->SummonCreature(s.entry, s.pos, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 3s))
      |                                    ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                      |
      |                                                      TempSummon*
[ 97%] Building CXX object src/server/scripts/CMakeFiles/scripts_northrend.dir/Northrend/Ulduar/Ulduar/ulduar.cpp.o
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/server/scripts/CMakeFiles/scripts_northrend.dir/build.make:2025: src/server/scripts/CMakeFiles/scripts_northrend.dir/Northrend/Ulduar/Ulduar/boss_thorim.cpp.o] Error 1