Build: fix warning
/home/runner/work/EG-Source/EG-Source/src/server/scripts/Custom/EG_commandscript.cpp: In static member function ‘static bool EG_commandscript::HandleVisuals(ChatHandler*, bool)’:
/home/runner/work/EG-Source/EG-Source/src/server/scripts/Custom/EG_commandscript.cpp:311:12: error: suggest explicit braces to avoid ambiguous ‘else’ [-Werror=dangling-else]
  311 |         if (flag != CustomFlags::CUSTOM_FLAG_NONE)
      |            ^
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
make[2]: *** [src/server/scripts/CMakeFiles/scripts_custom.dir/build.make:107: src/server/scripts/CMakeFiles/scripts_custom.dir/Custom/EG_commandscript.cpp.o] Error 1