Build: fix compile error
/home/runner/work/EG-Source/EG-Source/src/server/game/Custom/Transmogrification.cpp: In member function ‘bool Transmogrification::SuitableForTransmogrification(Player*, const ItemTemplate*) const’:
/home/runner/work/EG-Source/EG-Source/src/server/game/Custom/Transmogrification.cpp:468:24: error: ‘const struct ItemTemplate’ has no member named ‘Spells’
  468 |             if (proto->Spells[0].SpellId != 0)
      |                        ^~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:1031: src/server/game/CMakeFiles/game.dir/Custom/Transmogrification.cpp.o] Error 1