Build: fix compile error
FAILED: [code=1] src/server/game/CMakeFiles/game.dir/Custom/CustomFunctions.cpp.o
/usr/bin/g++-13 -DBOOST_ALL_NO_LIB -DBOOST_ASIO_NO_DEPRECATED -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_BIND_NO_PLACEHOLDERS -DBOOST_CHRONO_DYN_LINK -DBOOST_CHRONO_NO_LIB -DBOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_FILESYSTEM_NO_LIB -DBOOST_LOCALE_DYN_LINK -DBOOST_LOCALE_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_USE_UTF8 -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DHAVE_SSE2 -DSFMT_MEXP=19937 -DTRINITY_API_EXPORT_GAME -DTRINITY_API_USE_DYNAMIC_LINKING -DTRINITY_BUILD_HAS_DEBUG_INFO=1 -DTRINITY_BUILD_TYPE=\"Debug\" -D__SSE2__ -I/home/runner/work/EG-Source/EG-Source/bin/src/server/game -I/home/runner/work/EG-Source/EG-Source/src/server/game -I/home/runner/work/EG-Source/EG-Source/src/server/game/AI -I/home/runner/work/EG-Source/EG-Source/src/server/game/AI/CoreAI -I/home/runner/work/EG-Source/EG-Source/src/server/game/AI/PlayerAI -I/home/runner/work/EG-Source/EG-Source/src/server/game/AI/ScriptedAI -I/home/runner/work/EG-Source/EG-Source/src/server/game/AI/SmartScripts -I/home/runner/work/EG-Source/EG-Source/src/server/game/Accounts -I/home/runner/work/EG-Source/EG-Source/src/server/game/Achievements -I/home/runner/work/EG-Source/EG-Source/src/server/game/Addons -I/home/runner/work/EG-Source/EG-Source/src/server/game/AuctionHouse -I/home/runner/work/EG-Source/EG-Source/src/server/game/AuctionHouseBot -I/home/runner/work/EG-Source/EG-Source/src/server/game/Battlefield -I/home/runner/work/EG-Source/EG-Source/src/server/game/Battlegrounds -I/home/runner/work/EG-Source/EG-Source/src/server/game/Battlegrounds/Zones -I/home/runner/work/EG-Source/EG-Source/src/server/game/Cache -I/home/runner/work/EG-Source/EG-Source/src/server/game/Calendar -I/home/runner/work/EG-Source/EG-Source/src/server/game/Chat -I/home/runner/work/EG-Source/EG-Source/src/server/game/Chat/Channels -I/home/runner/work/EG-Source/EG-Source/src/server/game/Chat/ChatCommands -I/home/runner/work/EG-Source/EG-Source/src/server/game/Combat -I/home/runner/work/EG-Source/EG-Source/src/server/game/Conditions -I/home/runner/work/EG-Source/EG-Source/src/server/game/Custom -I/home/runner/work/EG-Source/EG-Source/src/server/game/Custom/Anticheat -I/home/runner/work/EG-Source/EG-Source/src/server/game/DataStores -I/home/runner/work/EG-Source/EG-Source/src/server/game/DungeonFinding -I/home/runner/work/EG-Source/EG-Source/src/server/game/Entities -I/home/runner/work/EG-Source/EG-Source/src/server/game/Entities/Corpse -I/home/runner/work/EG-Source/EG-Source/src/server/game/Entities/Creature -I/home/runner/work/EG-Source/EG-Source/src/server/game/Entities/DynamicObject -I/home/runner/work/EG-Source/EG-Source/src/server/game/Entities/GameObject -I/home/runner/work/EG-Source/EG-Source/src/server/game/Entities/Item -I/home/runner/work/EG-Source/EG-Source/src/server/game/Entities/Item/Container -I/home/runner/work/EG-Source/EG-Source/src/server/game/Entities/Object -I/home/runner/work/EG-Source/EG-Source/src/server/game/Entities/Object/Updates -I/home/runner/work/EG-Source/EG-Source/src/server/game/Entities/Pet -I/home/runner/work/EG-Source/EG-Source/src/server/game/Entities/Player -I/home/runner/work/EG-Source/EG-Source/src/server/game/Entities/Totem -I/home/runner/work/EG-Source/EG-Source/src/server/game/Entities/Transport -I/home/runner/work/EG-Source/EG-Source/src/server/game/Entities/Unit -I/home/runner/work/EG-Source/EG-Source/src/server/game/Entities/Vehicle -I/home/runner/work/EG-Source/EG-Source/src/server/game/Events -I/home/runner/work/EG-Source/EG-Source/src/server/game/Globals -I/home/runner/work/EG-Source/EG-Source/src/server/game/Grids -I/home/runner/work/EG-Source/EG-Source/src/server/game/Grids/Cells -I/home/runner/work/EG-Source/EG-Source/src/server/game/Grids/Dynamic -I/home/runner/work/EG-Source/EG-Source/src/server/game/Grids/Notifiers -I/home/runner/work/EG-Source/EG-Source/src/server/game/Groups -I/home/runner/work/EG-Source/EG-Source/src/server/game/Guilds -I/home/runner/work/EG-Source/EG-Source/src/server/game/Handlers -I/home/runner/work/EG-Source/EG-Source/src/server/game/Instances -I/home/runner/work/EG-Source/EG-Source/src/server/game/Loot -I/home/runner/work/EG-Source/EG-Source/src/server/game/Mails -I/home/runner/work/EG-Source/EG-Source/src/server/game/Maps -I/home/runner/work/EG-Source/EG-Source/src/server/game/Miscellaneous -I/home/runner/work/EG-Source/EG-Source/src/server/game/Movement -I/home/runner/work/EG-Source/EG-Source/src/server/game/Movement/MovementGenerators -I/home/runner/work/EG-Source/EG-Source/src/server/game/Movement/Spline -I/home/runner/work/EG-Source/EG-Source/src/server/game/Movement/Waypoints -I/home/runner/work/EG-Source/EG-Source/src/server/game/OutdoorPvP -I/home/runner/work/EG-Source/EG-Source/src/server/game/Petitions -I/home/runner/work/EG-Source/EG-Source/src/server/game/Pools -I/home/runner/work/EG-Source/EG-Source/src/server/game/Quests -I/home/runner/work/EG-Source/EG-Source/src/server/game/Reputation -I/home/runner/work/EG-Source/EG-Source/src/server/game/Scripting -I/home/runner/work/EG-Source/EG-Source/src/server/game/Server -I/home/runner/work/EG-Source/EG-Source/src/server/game/Server/Packets -I/home/runner/work/EG-Source/EG-Source/src/server/game/Server/Protocol -I/home/runner/work/EG-Source/EG-Source/src/server/game/Skills -I/home/runner/work/EG-Source/EG-Source/src/server/game/Spells -I/home/runner/work/EG-Source/EG-Source/src/server/game/Spells/Auras -I/home/runner/work/EG-Source/EG-Source/src/server/game/Storages -I/home/runner/work/EG-Source/EG-Source/src/server/game/Texts -I/home/runner/work/EG-Source/EG-Source/src/server/game/Tickets -I/home/runner/work/EG-Source/EG-Source/src/server/game/Time -I/home/runner/work/EG-Source/EG-Source/src/server/game/Tools -I/home/runner/work/EG-Source/EG-Source/src/server/game/Warden -I/home/runner/work/EG-Source/EG-Source/src/server/game/Warden/Modules -I/home/runner/work/EG-Source/EG-Source/src/server/game/Weather -I/home/runner/work/EG-Source/EG-Source/src/server/game/World -I/home/runner/work/EG-Source/EG-Source/src/server/shared -I/home/runner/work/EG-Source/EG-Source/src/server/shared/DataStores -I/home/runner/work/EG-Source/EG-Source/src/server/shared/Dynamic -I/home/runner/work/EG-Source/EG-Source/src/server/shared/Dynamic/LinkedReference -I/home/runner/work/EG-Source/EG-Source/src/server/shared/Networking -I/home/runner/work/EG-Source/EG-Source/src/server/shared/Networking/ConnectionInitializers -I/home/runner/work/EG-Source/EG-Source/src/server/shared/Packets -I/home/runner/work/EG-Source/EG-Source/src/server/shared/Realm -I/home/runner/work/EG-Source/EG-Source/src/server/shared/Secrets -I/home/runner/work/EG-Source/EG-Source/src/server/database -I/home/runner/work/EG-Source/EG-Source/src/server/database/Database -I/home/runner/work/EG-Source/EG-Source/src/server/database/Database/Implementation -I/home/runner/work/EG-Source/EG-Source/src/server/database/Logging -I/home/runner/work/EG-Source/EG-Source/src/server/database/Updater -I/home/runner/work/EG-Source/EG-Source/bin -I/home/runner/work/EG-Source/EG-Source/src/common -I/home/runner/work/EG-Source/EG-Source/src/common/Asio -I/home/runner/work/EG-Source/EG-Source/src/common/Collision -I/home/runner/work/EG-Source/EG-Source/src/common/Collision/Management -I/home/runner/work/EG-Source/EG-Source/src/common/Collision/Maps -I/home/runner/work/EG-Source/EG-Source/src/common/Collision/Models -I/home/runner/work/EG-Source/EG-Source/src/common/Configuration -I/home/runner/work/EG-Source/EG-Source/src/common/Containers -I/home/runner/work/EG-Source/EG-Source/src/common/Containers/Utilities -I/home/runner/work/EG-Source/EG-Source/src/common/Cryptography -I/home/runner/work/EG-Source/EG-Source/src/common/Cryptography/Authentication -I/home/runner/work/EG-Source/EG-Source/src/common/DataStores -I/home/runner/work/EG-Source/EG-Source/src/common/Debugging -I/home/runner/work/EG-Source/EG-Source/src/common/Debugging/Windows -I/home/runner/work/EG-Source/EG-Source/src/common/Encoding -I/home/runner/work/EG-Source/EG-Source/src/common/IPLocation -I/home/runner/work/EG-Source/EG-Source/src/common/Logging -I/home/runner/work/EG-Source/EG-Source/src/common/Metric -I/home/runner/work/EG-Source/EG-Source/src/common/Platform -I/home/runner/work/EG-Source/EG-Source/src/common/Platform/Windows -I/home/runner/work/EG-Source/EG-Source/src/common/Threading -I/home/runner/work/EG-Source/EG-Source/src/common/Time -I/home/runner/work/EG-Source/EG-Source/src/common/Utilities -I/home/runner/work/EG-Source/EG-Source/bin/dep/jemalloc/include -I/home/runner/work/EG-Source/EG-Source/dep/valgrind -I/home/runner/work/EG-Source/EG-Source/dep/argon2 -I/home/runner/work/EG-Source/EG-Source/dep/fmt/include -I/home/runner/work/EG-Source/EG-Source/dep/g3dlite/include -I/home/runner/work/EG-Source/EG-Source/dep/recastnavigation/Detour/Include -I/home/runner/work/EG-Source/EG-Source/dep/SFMT -I/home/runner/work/EG-Source/EG-Source/dep/utf8cpp -I/home/runner/work/EG-Source/EG-Source/dep/short_alloc -I/home/runner/work/EG-Source/EG-Source/dep/efsw/include -DNDEBUG -g0 -std=c++20 -fPIC -fno-delete-null-pointer-checks -fPIC -Wno-attributes -W -Wall -Wextra -Winit-self -Winvalid-pch -Wfatal-errors -Woverloaded-virtual -Wno-missing-field-initializers -Wno-maybe-uninitialized -Werror -MD -MT src/server/game/CMakeFiles/game.dir/Custom/CustomFunctions.cpp.o -MF src/server/game/CMakeFiles/game.dir/Custom/CustomFunctions.cpp.o.d -o src/server/game/CMakeFiles/game.dir/Custom/CustomFunctions.cpp.o -c /home/runner/work/EG-Source/EG-Source/src/server/game/Custom/CustomFunctions.cpp
/home/runner/work/EG-Source/EG-Source/src/server/game/Custom/CustomFunctions.cpp: In member function ‘void Creature::LoadCreaturesAddonAuras()’:
/home/runner/work/EG-Source/EG-Source/src/server/game/Custom/CustomFunctions.cpp:91:48: error: ‘sSpellMgr’ was not declared in this scope; did you mean ‘SpellMgr’?
   91 |         SpellInfo const* AdditionalSpellInfo = sSpellMgr->GetSpellInfo(*itr);
      |                                                ^~~~~~~~~
      |                                                SpellMgr
compilation terminated due to -Wfatal-errors.