Build: fix warning
/home/runner/work/EG-Source/EG-Source/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_rend_blackhand.cpp: In member function ‘virtual void boss_rend_blackhand::JustSummoned(Creature*)’:
/home/runner/work/EG-Source/EG-Source/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_rend_blackhand.cpp:194:18: error: variable ‘summonPos’ set but not used [-Werror=unused-but-set-variable]
  194 |         Position summonPos = me->GetPosition();
      |                  ^~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
make[2]: *** [src/server/scripts/CMakeFiles/scripts_easternkingdoms.dir/build.make:597: src/server/scripts/CMakeFiles/scripts_easternkingdoms.dir/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_rend_blackhand.cpp.o] Error 1