Scripts/UtgardePinnacle: fix typo in 7d637b22bc1c3c484c1a88f234c1951eff9d78aa
missing brackets

/home/runner/work/EG-Source/EG-Source/src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_skadi.cpp: In member function ‘virtual void boss_skadi::JustSummoned(Creature*)’:
/home/runner/work/EG-Source/EG-Source/src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_skadi.cpp:186:17: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
  186 |                 if (firstWaveSummoned)
      |                 ^~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
make[2]: *** [src/server/scripts/CMakeFiles/scripts_northrend.dir/build.make:2179: src/server/scripts/CMakeFiles/scripts_northrend.dir/Northrend/UtgardeKeep/UtgardePinnacle/boss_skadi.cpp.o] Error 1